server:
  port: 8761

spring:
  application:
    name: nacos-provider
  cloud:
    # nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8100


